library(maptools)
data(wrld_simpl)
library(spbabel)
library(dplyr)
xtab <- sptable(wrld_simpl)
abline(v = 90, h = 0)
seindex <- dplyr::filter(xtab, x > 100 & y < 0) %>% distinct(object)
seatt <- seindex %>% inner_join(as.data.frame(wrld_simpl) %>% mutate(object = row_number()))
semap <- xtab %>% filter(object %in% seatt$object)

devtools::use_data(semap, overwrite = TRUE)
devtools::use_data(seatt, overwrite = TRUE)
